version: '3.1'
services:
    db:
        image: mysql:8.0
        container_name: mysql-kotlin-forum
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports: 
        -  "3306:3306"
        volumes:
        - alura_data:/var/lib/mysql

volumes:
    alura_data: